### ISSUE TITLE
6.5 merge conflicts

### ISSUE THREAD

**Issue by wozaiha** [ottercorp/DalamudPluginsD17#181]
- [ ] 1. AdventurerInNeed
- [ ] 2. BetterPartyFinder
- [ ] 3. BetterPlaytime
- [ ] 4. CharacterPanelRefined
- [ ] 5. CurrencyTracker
- [ ] 6. DailyDuty
- [ ] 7. DeepDungeonTracker
- [ ] 8. Distance
- [ ] 9. EngageTimer
- [ ] 10. EurekaHelper
- [ ] 11. FPSPlugin
- [x] 12. GatherBuddy
- [ ] 13. Hunty
- [ ] 14. JustBackup
- [ ] 15. Mappy
- [ ] 16. MPTickBar
- [ ] 17. NoTankYou
- [ ] 18. OBS
- [ ] 19. Orchestrion
- [ ] 20. PingPlugin
- [ ] 21. PixelPerfect
- [ ] 22. PrefPro
- [ ] 23. RemotePartyFinder
- [ ] 24. RezPls
- [x] 25. SimpleTweaksPlugin
- [ ] 26. SubmarineTracker
- [ ] 27. TrackyTrack
- [ ] 28. UsedName
- [ ] 29. VFXEditor
- [x] 30. Visibility
- [ ] 31. WaymarkPresetPlugin
- [ ] 32. WinTitle
- [ ] 33. WorkshopOptimizerPlugin
- [ ] 34. BetterTargetingSystem
- [ ] 35. casexile
- [ ] 36. HUDManager
- [ ] 37. WhereIsMyMouse
- [ ] 38. XIVWindowResizer

爆炸中：

- [ ] PriceInsightCN 
- [ ] DeepDungeonTracker 
- [x] VFXEditorCN 
- [ ] ChatTranslated 
- [ ] LogogramHelperCN

**Comment by Bluefissure** [comment]
https://github.com/ottercorp/DalamudPluginsD17/pull/188

**Comment by pekoprincess** [comment]
report about 19. Orchestrion
![image](https://github.com/ottercorp/DalamudPluginsD17/assets/64051828/7888693e-a66e-4592-8819-f1426271e7ec)
File missed
![image](https://github.com/ottercorp/DalamudPluginsD17/assets/64051828/1ec338d5-bbb2-4f51-9e7e-37b61a07b2b8)
Request from google doc
![image](https://github.com/ottercorp/DalamudPluginsD17/assets/64051828/162103b9-7015-4470-8ed7-e6e7d1c758a5)
Because amost user cannot access google.
pack this file into the package, and update repo
ty
